### ISSUE TITLE
bleichenbacher possible issue (?!)

### ISSUE THREAD

**Issue by apasare** [zweisamkeit/RSHack#2]
Didn't really test this, but looking at code something bothered me, on line 154 the return of `Iteration` is assigned to `M`, but the `Iteration` function doesn't seem to return anything, is this intended?

https://github.com/zweisamkeit/RSHack/blob/a18870004854c9b82deaf689e181f2a01fe4741d/Attacks/Bleichenbacher/bleichenbacher.py#L154

**Comment by zweisamkeit** [comment]
Hi godvsdeity,
Indeed, this assignment was useless. Probably a remnant of an old version.
However, the program was working properly.
Thanks for reporting!
