### ISSUE TITLE
ModuleNotFoundError: No module named 'comod'

### ISSUE THREAD

**Issue by nioupola** [zweisamkeit/RSHack#5]
Hello,

This module doesn't seem available anymore. I can't find any information about it and I can't install it through `pip`. I tried with both python2 and python3.

Thanks in advance

**Comment by zweisamkeit** [comment]
Hi Darkitty,

"comod" is the local Common Modulus class (see https://github.com/zweisamkeit/RSHack/blob/master/Attacks/Common_Modulus/comod.py).


Can you check that all the files are present in the current directory? It should be automatically imported by the main program.

Regards,

**Comment by nioupola** [comment]
Hi,

Indeed. I clone again the repo and it works fine again. Thanks for the help.

Happy new year :fireworks: :sparkles:
